// ============================================================================
// C#: ConsoleCellInstance
// Total Size: 28 bytes (constant buffer)
// Generated: 2026-04-15T17:19:21.224594
// Generated by StructToolset - DO NOT EDIT MANUALLY
// ============================================================================

using System;
using System.Runtime.InteropServices;
using UnityEngine;

namespace CinematicShaders.Native.Structs
{
    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public struct ConsoleCellInstanceNative
    {
        public ushort GridX;  // Grid column index
        public ushort GridY;  // Grid row index
        public ushort GlyphID;  // Stable glyph ID from TextSystem
        public ushort _pad1;  // Padding to 4-byte boundary
        public uint Color;  // Packed ARGB color
        public float U0;  // Atlas UV left
        public float V0;  // Atlas UV top
        public float U1;  // Atlas UV right
        public float V1;  // Atlas UV bottom
    }
}

// Runtime size verification (call at startup):
// System.Diagnostics.Debug.Assert(Marshal.SizeOf(typeof(ConsoleCellInstanceNative)) == 28,
//     $"ConsoleCellInstanceNative size mismatch");
