// ============================================================================
// C#: KartographerParams
// Total Size: 1024 bytes (constant buffer)
// Generated by StructToolset - DO NOT EDIT MANUALLY
// ============================================================================

using System;
using System.Runtime.InteropServices;
using UnityEngine;

namespace CinematicShaders.Native.Structs
{
    [StructLayout(LayoutKind.Sequential, Pack = 16)]
    public struct KartographerParamsNative
    {
        // Field offsets (bytes):
        //     0: ResolutionX (float) // Screen width in pixels
        //     4: ResolutionY (float) // Screen height in pixels
        //     8: Time (float) // Current time in seconds
        //    12: GridIntensity (float) // Grid line brightness
        //    16: GridThickness (float) // Grid line thickness
        //    20: ChromaticAberrationStrength (float) // CA effect strength
        //    24: VignetteStrength (float) // Vignette darkness
        //    28: VignetteStart (float) // Vignette inner radius
        //    32: VignetteEnd (float) // Vignette outer radius
        //    36: PreRotationYaw (float) // Grid yaw rotation
        //    40: PreRotationPitch (float) // Grid pitch rotation
        //    44: GridSizePreset (int) // Grid density preset
        //    48: GridColorIndex (int) // Grid color selection
        //    52: _pad1 (float) // Padding
        //    56: _pad2 (float) // Padding
        //    60: _padAlignCamera (float) // Align to 16 bytes
        //    64: CameraRightX (float) // Camera right vector X
        //    68: CameraRightY (float) // Camera right vector Y
        //    72: CameraRightZ (float) // Camera right vector Z
        //    76: _pad3 (float) // Padding
        //    80: CameraUpX (float) // Camera up vector X
        //    84: CameraUpY (float) // Camera up vector Y
        //    88: CameraUpZ (float) // Camera up vector Z
        //    92: _pad4 (float) // Padding
        //    96: CameraForwardX (float) // Camera forward vector X
        //   100: CameraForwardY (float) // Camera forward vector Y
        //   104: CameraForwardZ (float) // Camera forward vector Z
        //   108: _pad5 (float) // Padding
        //   112: DebugShapesEnabled (int) // Show debug overlays
        //   116: _pad6 (float) // Padding
        //   120: _pad7 (float) // Padding
        //   124: _pad8 (float) // Padding
        //   128: DebugCircleCenterX (float) // Debug circle X
        //   132: DebugCircleCenterY (float) // Debug circle Y
        //   136: DebugCircleRadius (float) // Debug circle radius
        //   140: DebugCircleThickness (float) // Debug circle line thickness
        //   144: DebugBoxTopLeftX (float) // Debug box X
        //   148: DebugBoxTopLeftY (float) // Debug box Y
        //   152: DebugBoxSizeX (float) // Debug box width
        //   156: DebugBoxSizeY (float) // Debug box height
        //   160: DebugBoxThickness (float) // Debug box line thickness
        //   164: DebugShapeIntensity (float) // Debug shape brightness
        //   168: _pad9 (float) // Padding
        //   172: FocalLength (float) // Camera focal length
        //   176: SelectionCircleEnabled (int) // Show selection circle
        //   180: SelectionStarHash (float) // Hash for flicker variation
        //   184: _padSelection2 (float) // Padding
        //   188: _padSelection3 (float) // Padding
        //   192: SelectionCircleCenterX (float) // Selection circle X
        //   196: SelectionCircleCenterY (float) // Selection circle Y
        //   200: SelectionCircleT (float) // Animation time 0-1
        //   204: SelectionCircleIntensity (float) // Circle brightness
        //   208: SelectionCircleThickness (float) // Circle line thickness
        //   212: SelectionCircleRadius (float) // Circle radius
        //   216: _padSelection4 (float) // Padding
        //   220: _padSelection5 (float) // Padding
        //   224: _padSelection6 (float) // Padding
        //   228: _padSelection7 (float) // Padding
        //   232: TextOriginX (float) // Text position X
        //   236: TextOriginY (float) // Text position Y
        //   240: TextAreaSizeX (float) // Text area width
        //   244: TextAreaSizeY (float) // Text area height
        //   248: SelectionTextT (float) // Text animation time
        //   252: GridLabelEnabledMask (uint) // Bit mask for enabled labels
        //   256: _padGridMask1 (float) // Padding
        //   260: _padGridMask2 (float) // Padding
        //   264: _padGridMask3 (float) // Padding
        //   268: _padGridMask4 (float) // Padding to align labels to 16 bytes
        //   272: GridLabel0_PosTangentX (Vector4) // Label 0 position + sizeX
        //   288: GridLabel0_TangentY (Vector4) // Label 0 tangent + sizeY
        //   304: GridLabel1_PosTangentX (Vector4) // Label 1 position + sizeX
        //   320: GridLabel1_TangentY (Vector4) // Label 1 tangent + sizeY
        //   336: GridLabel2_PosTangentX (Vector4) // Label 2 position + sizeX
        //   352: GridLabel2_TangentY (Vector4) // Label 2 tangent + sizeY
        //   368: GridLabel3_PosTangentX (Vector4) // Label 3 position + sizeX
        //   384: GridLabel3_TangentY (Vector4) // Label 3 tangent + sizeY
        //   400: GridLabel4_PosTangentX (Vector4) // Label 4 position + sizeX
        //   416: GridLabel4_TangentY (Vector4) // Label 4 tangent + sizeY
        //   432: GridLabel5_PosTangentX (Vector4) // Label 5 position + sizeX
        //   448: GridLabel5_TangentY (Vector4) // Label 5 tangent + sizeY
        //   464: GridLabel6_PosTangentX (Vector4) // Label 6 position + sizeX
        //   480: GridLabel6_TangentY (Vector4) // Label 6 tangent + sizeY
        //   496: GridLabel7_PosTangentX (Vector4) // Label 7 position + sizeX
        //   512: GridLabel7_TangentY (Vector4) // Label 7 tangent + sizeY
        //   528: GridLabel8_PosTangentX (Vector4) // Label 8 position + sizeX
        //   544: GridLabel8_TangentY (Vector4) // Label 8 tangent + sizeY
        //   560: GridLabel9_PosTangentX (Vector4) // Label 9 position + sizeX
        //   576: GridLabel9_TangentY (Vector4) // Label 9 tangent + sizeY
        //   592: GridLabel10_PosTangentX (Vector4) // Label 10 position + sizeX
        //   608: GridLabel10_TangentY (Vector4) // Label 10 tangent + sizeY
        //   624: GridLabel11_PosTangentX (Vector4) // Label 11 position + sizeX
        //   640: GridLabel11_TangentY (Vector4) // Label 11 tangent + sizeY
        //   656: GridLabelDebugMask (uint) // Bit mask for debug visualization
        //   660: LabelIntensity0 (float) // Label 0 brightness
        //   664: LabelIntensity1 (float) // Label 1 brightness
        //   668: LabelIntensity2 (float) // Label 2 brightness
        //   672: LabelIntensity3 (float) // Label 3 brightness
        //   676: LabelIntensity4 (float) // Label 4 brightness
        //   680: LabelIntensity5 (float) // Label 5 brightness
        //   684: LabelIntensity6 (float) // Label 6 brightness
        //   688: LabelIntensity7 (float) // Label 7 brightness
        //   692: LabelIntensity8 (float) // Label 8 brightness
        //   696: LabelIntensity9 (float) // Label 9 brightness
        //   700: LabelIntensity10 (float) // Label 10 brightness
        //   704: LabelIntensity11 (float) // Label 11 brightness
        //   708: LabelColor0 (uint) // Label 0 color override (ARGB)
        //   712: LabelColor1 (uint) // Label 1 color override (ARGB)
        //   716: LabelColor2 (uint) // Label 2 color override (ARGB)
        //   720: LabelColor3 (uint) // Label 3 color override (ARGB)
        //   724: LabelColor4 (uint) // Label 4 color override (ARGB)
        //   728: LabelColor5 (uint) // Label 5 color override (ARGB)
        //   732: LabelColor6 (uint) // Label 6 color override (ARGB)
        //   736: LabelColor7 (uint) // Label 7 color override (ARGB)
        //   740: LabelColor8 (uint) // Label 8 color override (ARGB)
        //   744: LabelColor9 (uint) // Label 9 color override (ARGB)
        //   748: LabelColor10 (uint) // Label 10 color override (ARGB)
        //   752: LabelColor11 (uint) // Label 11 color override (ARGB)
        //   756: VesselTargetEnabled (int) // Show vessel target selector
        //   760: VesselTargetHash (float) // Hash for flicker variation
        //   764: _padVessel1 (float) // Padding
        //   768: _padVessel2 (float) // Padding
        //   772: VesselTargetCircleCenterX (float) // Vessel target circle X
        //   776: VesselTargetCircleCenterY (float) // Vessel target circle Y
        //   780: VesselTargetCircleT (float) // Vessel target animation time 0-1
        //   784: VesselTargetCircleIntensity (float) // Vessel target circle brightness
        //   788: VesselTargetCircleThickness (float) // Vessel target circle line thickness
        //   792: VesselTargetCircleRadius (float) // Vessel target circle radius
        //   796: _padVessel3 (float) // Padding
        //   800: _padVessel4 (float) // Padding
        //   804: _padVessel5 (float) // Padding
        //   808: _padVessel6 (float) // Padding
        //   812: VesselTargetBoxTopLeftX (float) // Vessel target box X
        //   816: VesselTargetBoxTopLeftY (float) // Vessel target box Y
        //   820: VesselTargetBoxSizeX (float) // Vessel target box width
        //   824: VesselTargetBoxSizeY (float) // Vessel target box height
        //   828: VesselTargetBoxThickness (float) // Vessel target box line thickness
        //   832: _padVessel7 (float) // Padding
        //   836: VesselTargetTextOriginX (float) // Vessel target text position X
        //   840: VesselTargetTextOriginY (float) // Vessel target text position Y
        //   844: VesselTargetTextAreaSizeX (float) // Vessel target text area width
        //   848: VesselTargetTextAreaSizeY (float) // Vessel target text area height
        //   852: VesselTargetTextT (float) // Vessel target text animation time
        //   856: AnimatedLabelIntensity (float) // Generic intensity for animated labels (0-1)
        //   860: _padAnimated1 (float) // Padding
        //   864: _padAnimated2 (float) // Padding
        //   868: _padAnimated3 (float) // Padding to align to 16 bytes
        //   872: NavballEnabledMask (int) // Bits 0-6: prograde, retrograde, normal, antinormal, radial_in, radial_out, maneuver
        //   876: NavballOffscreenMode (int) // 0=world-space (disappear off-screen), 1=edge-clamp
        //   880: NavballIconSize (float) // Screen-space size in NDC units
        //   884: NavballIconThickness (float) // SDF edge thickness
        //   888: NavballMinIntensity (float) // Minimum intensity when far off-center (default 0.33)
        //   892: NavballMaxAngle (float) // Angle for min intensity in degrees (default 90)
        //   896: NavballHysteresisMargin (float) // Buffer zone for edge transition (default 0.05)
        //   900: _padNavball1 (float) // Padding to 16-byte boundary
        //   904: NavballIcon0_X (float) // Screen X in NDC (-aspect to aspect)
        //   908: NavballIcon0_Y (float) // Screen Y in NDC (-1 to 1)
        //   912: NavballIcon0_Intensity (float) // Current intensity (0 = disabled/hidden)
        //   916: NavballIcon0_Color (uint) // Packed ARGB color override (0 = use grid color)
        //   920: NavballIcon1_X (float) // Screen X in NDC
        //   924: NavballIcon1_Y (float) // Screen Y in NDC
        //   928: NavballIcon1_Intensity (float) // Current intensity
        //   932: NavballIcon1_Color (uint) // Packed ARGB color override
        //   936: NavballIcon2_X (float) // Screen X in NDC
        //   940: NavballIcon2_Y (float) // Screen Y in NDC
        //   944: NavballIcon2_Intensity (float) // Current intensity
        //   948: NavballIcon2_Color (uint) // Packed ARGB color override
        //   952: NavballIcon3_X (float) // Screen X in NDC
        //   956: NavballIcon3_Y (float) // Screen Y in NDC
        //   960: NavballIcon3_Intensity (float) // Current intensity
        //   964: NavballIcon3_Color (uint) // Packed ARGB color override
        //   968: NavballIcon4_X (float) // Screen X in NDC
        //   972: NavballIcon4_Y (float) // Screen Y in NDC
        //   976: NavballIcon4_Intensity (float) // Current intensity
        //   980: NavballIcon4_Color (uint) // Packed ARGB color override
        //   984: NavballIcon5_X (float) // Screen X in NDC
        //   988: NavballIcon5_Y (float) // Screen Y in NDC
        //   992: NavballIcon5_Intensity (float) // Current intensity
        //   996: NavballIcon5_Color (uint) // Packed ARGB color override
        //   1000: NavballIcon6_X (float) // Screen X in NDC
        //   1004: NavballIcon6_Y (float) // Screen Y in NDC
        //   1008: NavballIcon6_Intensity (float) // Current intensity (0 when no node)
        //   1012: NavballIcon6_Color (uint) // Packed ARGB color override

        public float ResolutionX;
        public float ResolutionY;
        public float Time;
        public float GridIntensity;
        public float GridThickness;
        public float ChromaticAberrationStrength;
        public float VignetteStrength;
        public float VignetteStart;
        public float VignetteEnd;
        public float PreRotationYaw;
        public float PreRotationPitch;
        public int GridSizePreset;
        public int GridColorIndex;
        public float _pad1;
        public float _pad2;
        public float _padAlignCamera;
        public float CameraRightX;
        public float CameraRightY;
        public float CameraRightZ;
        public float _pad3;
        public float CameraUpX;
        public float CameraUpY;
        public float CameraUpZ;
        public float _pad4;
        public float CameraForwardX;
        public float CameraForwardY;
        public float CameraForwardZ;
        public float _pad5;
        public int DebugShapesEnabled;
        public float _pad6;
        public float _pad7;
        public float _pad8;
        public float DebugCircleCenterX;
        public float DebugCircleCenterY;
        public float DebugCircleRadius;
        public float DebugCircleThickness;
        public float DebugBoxTopLeftX;
        public float DebugBoxTopLeftY;
        public float DebugBoxSizeX;
        public float DebugBoxSizeY;
        public float DebugBoxThickness;
        public float DebugShapeIntensity;
        public float _pad9;
        public float FocalLength;
        public int SelectionCircleEnabled;
        public float SelectionStarHash;
        public float _padSelection2;
        public float _padSelection3;
        public float SelectionCircleCenterX;
        public float SelectionCircleCenterY;
        public float SelectionCircleT;
        public float SelectionCircleIntensity;
        public float SelectionCircleThickness;
        public float SelectionCircleRadius;
        public float _padSelection4;
        public float _padSelection5;
        public float _padSelection6;
        public float _padSelection7;
        public float TextOriginX;
        public float TextOriginY;
        public float TextAreaSizeX;
        public float TextAreaSizeY;
        public float SelectionTextT;
        public uint GridLabelEnabledMask;
        public float _padGridMask1;
        public float _padGridMask2;
        public float _padGridMask3;
        public float _padGridMask4;
        public Vector4 GridLabel0_PosTangentX;
        public Vector4 GridLabel0_TangentY;
        public Vector4 GridLabel1_PosTangentX;
        public Vector4 GridLabel1_TangentY;
        public Vector4 GridLabel2_PosTangentX;
        public Vector4 GridLabel2_TangentY;
        public Vector4 GridLabel3_PosTangentX;
        public Vector4 GridLabel3_TangentY;
        public Vector4 GridLabel4_PosTangentX;
        public Vector4 GridLabel4_TangentY;
        public Vector4 GridLabel5_PosTangentX;
        public Vector4 GridLabel5_TangentY;
        public Vector4 GridLabel6_PosTangentX;
        public Vector4 GridLabel6_TangentY;
        public Vector4 GridLabel7_PosTangentX;
        public Vector4 GridLabel7_TangentY;
        public Vector4 GridLabel8_PosTangentX;
        public Vector4 GridLabel8_TangentY;
        public Vector4 GridLabel9_PosTangentX;
        public Vector4 GridLabel9_TangentY;
        public Vector4 GridLabel10_PosTangentX;
        public Vector4 GridLabel10_TangentY;
        public Vector4 GridLabel11_PosTangentX;
        public Vector4 GridLabel11_TangentY;
        public uint GridLabelDebugMask;
        public float LabelIntensity0;
        public float LabelIntensity1;
        public float LabelIntensity2;
        public float LabelIntensity3;
        public float LabelIntensity4;
        public float LabelIntensity5;
        public float LabelIntensity6;
        public float LabelIntensity7;
        public float LabelIntensity8;
        public float LabelIntensity9;
        public float LabelIntensity10;
        public float LabelIntensity11;
        public uint LabelColor0;
        public uint LabelColor1;
        public uint LabelColor2;
        public uint LabelColor3;
        public uint LabelColor4;
        public uint LabelColor5;
        public uint LabelColor6;
        public uint LabelColor7;
        public uint LabelColor8;
        public uint LabelColor9;
        public uint LabelColor10;
        public uint LabelColor11;
        public int VesselTargetEnabled;
        public float VesselTargetHash;
        public float _padVessel1;
        public float _padVessel2;
        public float VesselTargetCircleCenterX;
        public float VesselTargetCircleCenterY;
        public float VesselTargetCircleT;
        public float VesselTargetCircleIntensity;
        public float VesselTargetCircleThickness;
        public float VesselTargetCircleRadius;
        public float _padVessel3;
        public float _padVessel4;
        public float _padVessel5;
        public float _padVessel6;
        public float VesselTargetBoxTopLeftX;
        public float VesselTargetBoxTopLeftY;
        public float VesselTargetBoxSizeX;
        public float VesselTargetBoxSizeY;
        public float VesselTargetBoxThickness;
        public float _padVessel7;
        public float VesselTargetTextOriginX;
        public float VesselTargetTextOriginY;
        public float VesselTargetTextAreaSizeX;
        public float VesselTargetTextAreaSizeY;
        public float VesselTargetTextT;
        public float AnimatedLabelIntensity;
        public float _padAnimated1;
        public float _padAnimated2;
        public float _padAnimated3;
        public int NavballEnabledMask;
        public int NavballOffscreenMode;
        public float NavballIconSize;
        public float NavballIconThickness;
        public float NavballMinIntensity;
        public float NavballMaxAngle;
        public float NavballHysteresisMargin;
        public float _padNavball1;
        public float NavballIcon0_X;
        public float NavballIcon0_Y;
        public float NavballIcon0_Intensity;
        public uint NavballIcon0_Color;
        public float NavballIcon1_X;
        public float NavballIcon1_Y;
        public float NavballIcon1_Intensity;
        public uint NavballIcon1_Color;
        public float NavballIcon2_X;
        public float NavballIcon2_Y;
        public float NavballIcon2_Intensity;
        public uint NavballIcon2_Color;
        public float NavballIcon3_X;
        public float NavballIcon3_Y;
        public float NavballIcon3_Intensity;
        public uint NavballIcon3_Color;
        public float NavballIcon4_X;
        public float NavballIcon4_Y;
        public float NavballIcon4_Intensity;
        public uint NavballIcon4_Color;
        public float NavballIcon5_X;
        public float NavballIcon5_Y;
        public float NavballIcon5_Intensity;
        public uint NavballIcon5_Color;
        public float NavballIcon6_X;
        public float NavballIcon6_Y;
        public float NavballIcon6_Intensity;
        public uint NavballIcon6_Color;
        
        // Padding to ensure 1024-byte total size (16-byte alignment)
        public uint _padding1;
        public uint _padding2;
    }
}

// Runtime size verification (call at startup):
// System.Diagnostics.Debug.Assert(Marshal.SizeOf(typeof(KartographerParamsNative)) == 1024,
//     $"KartographerParamsNative size mismatch");
