#!/usr/bin/env python3
"""
Code Generators
===============
Generates C++, HLSL, and C# code from struct layouts.
"""

from layout_engine import StructLayout, LayoutField, StructDef


class CPPGenerator:
    """Generates C++ struct code."""
    
    @staticmethod
    def generate(struct_def: StructDef, layout: StructLayout) -> str:
        import datetime
        lines = []
        
        lines.append("// ============================================================================")
        lines.append(f"// C++: {layout.name}")
        lines.append(f"// Total Size: {layout.total_size} bytes (constant buffer)")
        lines.append(f"// Generated: {datetime.datetime.now().isoformat()}")
        lines.append("// Generated by StructToolset - DO NOT EDIT MANUALLY")
        lines.append("// ============================================================================")
        lines.append("")
        lines.append("#pragma once")
        lines.append("#include <cstdint>")
        lines.append("")
        
        # HLSL-style vector types for C++
        lines.append("// HLSL-style vector types for C++")
        lines.append("#ifndef CINEMATICSHADERS_FLOAT2_DEFINED")
        lines.append("#define CINEMATICSHADERS_FLOAT2_DEFINED")
        lines.append("struct float2 { float x, y; };")
        lines.append("#endif")
        lines.append("#ifndef CINEMATICSHADERS_FLOAT3_DEFINED")
        lines.append("#define CINEMATICSHADERS_FLOAT3_DEFINED")
        lines.append("struct float3 { float x, y, z; };")
        lines.append("#endif")
        lines.append("#ifndef CINEMATICSHADERS_FLOAT4_DEFINED")
        lines.append("#define CINEMATICSHADERS_FLOAT4_DEFINED")
        lines.append("struct float4 { float x, y, z, w; };")
        lines.append("#endif")
        lines.append("")
        
        # Struct with pragma pack
        lines.append("#pragma pack(push, 16)")
        lines.append(f"struct {layout.name} {{")
        
        # Generate field declarations with comments inline
        current_base = None
        for field in layout.fields:
            comment = f"  // {field.comment}" if field.comment else ""
            if field.is_padding:
                # Emit padding as float with comment
                lines.append(f"    float {field.name};  // {field.size}-byte padding")
            elif '.' in field.name:
                base_name, component = field.name.split('.')
                if base_name != current_base:
                    # Starting a new vector
                    current_base = base_name
                    lines.append(f"    {field.type_name} {base_name}_{component};{comment}")
                else:
                    # Additional component - use different naming
                    lines.append(f"    {field.type_name} {base_name}_{component};")
            elif '[' in field.name and '].' in field.name:
                # Array of vectors - already expanded
                parts = field.name.replace(']', '').replace('[', '_').split('.')
                if len(parts) == 2:
                    arr_name, comp = parts
                    lines.append(f"    {field.type_name} {arr_name}_{comp};")
            else:
                current_base = None
                if field.array_size > 1:
                    lines.append(f"    {field.type_name} {field.name}[{field.array_size}];{comment}")
                else:
                    lines.append(f"    {field.type_name} {field.name};{comment}")
        
        lines.append("};")
        lines.append("#pragma pack(pop)")
        lines.append("")
        
        # Static assertions
        lines.append("// Static assertions to verify HLSL constant buffer alignment")
        lines.append(f"static_assert(sizeof({layout.name}) == {layout.total_size},")
        lines.append(f'              "{layout.name} size mismatch - expected {layout.total_size} bytes");')
        lines.append(f"static_assert(sizeof({layout.name}) % 16 == 0,")
        lines.append(f'              "{layout.name} must be 16-byte aligned for HLSL CB");')
        lines.append("")
        
        return "\n".join(lines)


class HLSLGenerator:
    """Generates HLSL struct code."""
    
    @staticmethod
    def generate(struct_def: StructDef, layout: StructLayout) -> str:
        import datetime
        lines = []
        
        lines.append("// ============================================================================")
        lines.append(f"// HLSL: {layout.name}")
        lines.append(f"// Total Size: {layout.total_size} bytes (constant buffer)")
        lines.append(f"// Generated: {datetime.datetime.now().isoformat()}")
        lines.append("// Generated by StructToolset - DO NOT EDIT MANUALLY")
        lines.append("// ============================================================================")
        lines.append("")
        
        # Calculate which fields can be coalesced into vectors
        vector_groups = HLSLGenerator._find_vector_groups(struct_def)
        vector_field_names = set()
        for base_name, fields in vector_groups.items():
            for f in fields:
                vector_field_names.add(f.name)
        
        lines.append(f"struct {layout.name} {{")
        
        # Output field declarations with vector coalescing and explicit padding
        skip_until = None
        for i, field in enumerate(layout.fields):
            if skip_until and field.name != skip_until:
                continue
            skip_until = None
            
            if field.is_padding:
                # Emit explicit padding to ensure alignment matches C#/C++
                pad_type = "float" if field.size == 4 else f"float{field.size // 4}"
                lines.append(f"    {pad_type} _padding_{field.offset};  // {field.size}-byte alignment padding")
                continue
            
            # Check if this starts a vector group
            is_vector_start = False
            vec_size = 0
            base_name = None
            for bn, vf in vector_groups.items():
                if vf and vf[0].name == field.name:
                    is_vector_start = True
                    vec_size = len(vf)
                    base_name = bn
                    break
            
            if is_vector_start:
                vec_type = f"float{vec_size}"
                comment = f"  // {field.comment}" if field.comment else ""
                lines.append(f"    {vec_type} {base_name};{comment}")
                # Skip vector components
                skip_until = vector_groups[base_name][-1].name
            elif field.name not in vector_field_names:
                # Regular field (not part of a vector)
                comment = f"  // {field.comment}" if field.comment else ""
                if field.array_size > 1:
                    lines.append(f"    {field.type_name} {field.name}[{field.array_size}];{comment}")
                else:
                    lines.append(f"    {field.type_name} {field.name};{comment}")
        
        lines.append("};")
        lines.append("")
        
        # Constant buffer declaration helper
        lines.append(f"// Constant buffer declaration:")
        lines.append(f"// cbuffer {layout.name}Buffer : register(b0) {{")
        lines.append(f"//     {layout.name} g_{layout.name[0].lower() + layout.name[1:]};")
        lines.append(f"// }}")
        lines.append("")
        
        return "\n".join(lines)
    
    @staticmethod
    def _find_vector_groups(struct_def: StructDef) -> dict:
        """
        Find groups of consecutive float fields that form vectors.
        Returns dict of base_name -> list of FieldDefs.
        
        Supports both patterns:
        - CameraRightX, CameraRightY, CameraRightZ (no underscore)
        - NavballIcon0_X, NavballIcon0_Y (with underscore)
        """
        groups = {}
        i = 0
        fields = struct_def.fields
        
        while i < len(fields):
            field = fields[i]
            
            # Look for X, Y, Z, W pattern (with or without underscore)
            if field.type_name == 'float' and field.array_size == 1:
                base = None
                suffixes = None
                
                if field.name.endswith('_X'):
                    # Pattern: BaseName_X, BaseName_Y, BaseName_Z, BaseName_W
                    base = field.name[:-2]  # Remove '_X'
                    suffixes = ['_X', '_Y', '_Z', '_W']
                elif field.name.endswith('X') and not field.name.endswith('_X'):
                    # Pattern: BaseNameX, BaseNameY, BaseNameZ, BaseNameW
                    base = field.name[:-1]  # Remove 'X'
                    suffixes = ['X', 'Y', 'Z', 'W']
                
                if base and suffixes:
                    # Check for consecutive components
                    found = [field]
                    
                    for j, suffix in enumerate(suffixes[1:], 1):
                        if i + j < len(fields):
                            next_field = fields[i + j]
                            expected_name = f"{base}{suffix}"
                            if next_field.name == expected_name and next_field.type_name == 'float':
                                found.append(next_field)
                            else:
                                break
                    
                    # Only group if we found at least 2 components
                    if len(found) >= 2:
                        groups[base] = found
                        i += len(found)
                        continue
            
            i += 1
        
        return groups


class CSGenerator:
    """Generates C# struct code."""
    
    @staticmethod
    def generate(struct_def: StructDef, layout: StructLayout, use_unity_types: bool = True) -> str:
        import datetime
        lines = []
        
        lines.append("// ============================================================================")
        lines.append(f"// C#: {layout.name}")
        lines.append(f"// Total Size: {layout.total_size} bytes (constant buffer)")
        lines.append(f"// Generated: {datetime.datetime.now().isoformat()}")
        lines.append("// Generated by StructToolset - DO NOT EDIT MANUALLY")
        lines.append("// ============================================================================")
        lines.append("")
        lines.append("using System;")
        lines.append("using System.Runtime.InteropServices;")
        if use_unity_types:
            lines.append("using UnityEngine;")
        lines.append("")
        lines.append("namespace CinematicShaders.Native.Structs")
        lines.append("{")
        lines.append(f"    [StructLayout(LayoutKind.Sequential, Pack = 16)]")
        lines.append(f"    public struct {layout.name}Native")
        lines.append("    {")
        
        # Output field declarations with comments inline
        for field in layout.fields:
            # Determine C# type
            if field.is_padding:
                # Padding fields are already uint from layout engine
                cs_type = 'uint'
            elif field.type_name == 'float4' and use_unity_types:
                cs_type = 'Vector4'
            elif field.type_name == 'float2' and use_unity_types:
                cs_type = 'Vector2'
            elif field.type_name == 'float3' and use_unity_types:
                cs_type = 'Vector3'
            elif field.type_name in ('uint32_t', 'uint'):
                cs_type = 'uint'
            elif field.type_name == 'int32_t':
                cs_type = 'int'
            elif field.type_name == 'bool':
                cs_type = 'int'  # C# bool is 1 byte, use int for HLSL interop
            else:
                cs_type = field.type_name
            
            if field.is_padding:
                comment = f"  // {field.size}-byte padding"
            elif field.comment:
                comment = f"  // {field.comment}"
            else:
                comment = ""
            lines.append(f"        public {cs_type} {field.name};{comment}")
        
        lines.append("    }")
        lines.append("}")
        lines.append("")
        
        # Size verification
        lines.append("// Runtime size verification (call at startup):")
        lines.append(f"// System.Diagnostics.Debug.Assert(Marshal.SizeOf(typeof({layout.name}Native)) == {layout.total_size},")
        lines.append(f'//     $"{layout.name}Native size mismatch");')
        lines.append("")
        
        return "\n".join(lines)
