// ============================================================================
// HLSL: ConsoleCellInstance
// Total Size: 28 bytes (constant buffer)
// Generated: 2026-04-15T17:19:21.224594
// Generated by StructToolset - DO NOT EDIT MANUALLY
// ============================================================================

struct ConsoleCellInstance {
    uint16 GridX;  // Grid column index
    uint16 GridY;  // Grid row index
    uint16 GlyphID;  // Stable glyph ID from TextSystem
    uint16 _pad1;  // Padding to 4-byte boundary
    uint32 Color;  // Packed ARGB color
    float U0;  // Atlas UV left
    float V0;  // Atlas UV top
    float U1;  // Atlas UV right
    float V1;  // Atlas UV bottom
};

// Constant buffer declaration:
// cbuffer ConsoleCellInstanceBuffer : register(b0) {
//     ConsoleCellInstance g_consoleCellInstance;
// }
