// ============================================================================
// C++: KartographerParams
// Total Size: 1024 bytes (constant buffer)
// Generated by StructToolset - DO NOT EDIT MANUALLY
// ============================================================================

#pragma once
#include <cstdint>

// HLSL-style vector types for C++
struct float2 { float x, y; };
struct float3 { float x, y, z; };
struct float4 { float x, y, z, w; };

#pragma pack(push, 16)
struct KartographerParams {
    // Field offsets (bytes):
    //     0: ResolutionX (float) // Screen width in pixels
    //     4: ResolutionY (float) // Screen height in pixels
    //     8: Time (float) // Current time in seconds
    //    12: GridIntensity (float) // Grid line brightness
    //    16: GridThickness (float) // Grid line thickness
    //    20: ChromaticAberrationStrength (float) // CA effect strength
    //    24: VignetteStrength (float) // Vignette darkness
    //    28: VignetteStart (float) // Vignette inner radius
    //    32: VignetteEnd (float) // Vignette outer radius
    //    36: PreRotationYaw (float) // Grid yaw rotation
    //    40: PreRotationPitch (float) // Grid pitch rotation
    //    44: GridSizePreset (int32_t) // Grid density preset
    //    48: GridColorIndex (int32_t) // Grid color selection
    //    52: _pad1 (float) // Padding
    //    56: _pad2 (float) // Padding
    //    60: _padAlignCamera (float) // Align to 16 bytes
    //    64: CameraRightX (float) // Camera right vector X
    //    68: CameraRightY (float) // Camera right vector Y
    //    72: CameraRightZ (float) // Camera right vector Z
    //    76: _pad3 (float) // Padding
    //    80: CameraUpX (float) // Camera up vector X
    //    84: CameraUpY (float) // Camera up vector Y
    //    88: CameraUpZ (float) // Camera up vector Z
    //    92: _pad4 (float) // Padding
    //    96: CameraForwardX (float) // Camera forward vector X
    //   100: CameraForwardY (float) // Camera forward vector Y
    //   104: CameraForwardZ (float) // Camera forward vector Z
    //   108: _pad5 (float) // Padding
    //   112: DebugShapesEnabled (int32_t) // Show debug overlays
    //   116: _pad6 (float) // Padding
    //   120: _pad7 (float) // Padding
    //   124: _pad8 (float) // Padding
    //   128: DebugCircleCenterX (float) // Debug circle X
    //   132: DebugCircleCenterY (float) // Debug circle Y
    //   136: DebugCircleRadius (float) // Debug circle radius
    //   140: DebugCircleThickness (float) // Debug circle line thickness
    //   144: DebugBoxTopLeftX (float) // Debug box X
    //   148: DebugBoxTopLeftY (float) // Debug box Y
    //   152: DebugBoxSizeX (float) // Debug box width
    //   156: DebugBoxSizeY (float) // Debug box height
    //   160: DebugBoxThickness (float) // Debug box line thickness
    //   164: DebugShapeIntensity (float) // Debug shape brightness
    //   168: _pad9 (float) // Padding
    //   172: FocalLength (float) // Camera focal length
    //   176: SelectionCircleEnabled (int32_t) // Show selection circle
    //   180: SelectionStarHash (float) // Hash for flicker variation
    //   184: _padSelection2 (float) // Padding
    //   188: _padSelection3 (float) // Padding
    //   192: SelectionCircleCenterX (float) // Selection circle X
    //   196: SelectionCircleCenterY (float) // Selection circle Y
    //   200: SelectionCircleT (float) // Animation time 0-1
    //   204: SelectionCircleIntensity (float) // Circle brightness
    //   208: SelectionCircleThickness (float) // Circle line thickness
    //   212: SelectionCircleRadius (float) // Circle radius
    //   216: _padSelection4 (float) // Padding
    //   220: _padSelection5 (float) // Padding
    //   224: _padSelection6 (float) // Padding
    //   228: _padSelection7 (float) // Padding
    //   232: TextOriginX (float) // Text position X
    //   236: TextOriginY (float) // Text position Y
    //   240: TextAreaSizeX (float) // Text area width
    //   244: TextAreaSizeY (float) // Text area height
    //   248: SelectionTextT (float) // Text animation time
    //   252: GridLabelEnabledMask (uint32_t) // Bit mask for enabled labels
    //   256: _padGridMask1 (float) // Padding
    //   260: _padGridMask2 (float) // Padding
    //   264: _padGridMask3 (float) // Padding
    //   268: _padGridMask4 (float) // Padding to align labels to 16 bytes
    //   272: GridLabel0_PosTangentX_x (float) // Label 0 position + sizeX
    //   276: GridLabel0_PosTangentX_y (float)
    //   280: GridLabel0_PosTangentX_z (float)
    //   284: GridLabel0_PosTangentX_w (float)
    //   288: GridLabel0_TangentY_x (float) // Label 0 tangent + sizeY
    //   292: GridLabel0_TangentY_y (float)
    //   296: GridLabel0_TangentY_z (float)
    //   300: GridLabel0_TangentY_w (float)
    //   304: GridLabel1_PosTangentX_x (float) // Label 1 position + sizeX
    //   308: GridLabel1_PosTangentX_y (float)
    //   312: GridLabel1_PosTangentX_z (float)
    //   316: GridLabel1_PosTangentX_w (float)
    //   320: GridLabel1_TangentY_x (float) // Label 1 tangent + sizeY
    //   324: GridLabel1_TangentY_y (float)
    //   328: GridLabel1_TangentY_z (float)
    //   332: GridLabel1_TangentY_w (float)
    //   336: GridLabel2_PosTangentX_x (float) // Label 2 position + sizeX
    //   340: GridLabel2_PosTangentX_y (float)
    //   344: GridLabel2_PosTangentX_z (float)
    //   348: GridLabel2_PosTangentX_w (float)
    //   352: GridLabel2_TangentY_x (float) // Label 2 tangent + sizeY
    //   356: GridLabel2_TangentY_y (float)
    //   360: GridLabel2_TangentY_z (float)
    //   364: GridLabel2_TangentY_w (float)
    //   368: GridLabel3_PosTangentX_x (float) // Label 3 position + sizeX
    //   372: GridLabel3_PosTangentX_y (float)
    //   376: GridLabel3_PosTangentX_z (float)
    //   380: GridLabel3_PosTangentX_w (float)
    //   384: GridLabel3_TangentY_x (float) // Label 3 tangent + sizeY
    //   388: GridLabel3_TangentY_y (float)
    //   392: GridLabel3_TangentY_z (float)
    //   396: GridLabel3_TangentY_w (float)
    //   400: GridLabel4_PosTangentX_x (float) // Label 4 position + sizeX
    //   404: GridLabel4_PosTangentX_y (float)
    //   408: GridLabel4_PosTangentX_z (float)
    //   412: GridLabel4_PosTangentX_w (float)
    //   416: GridLabel4_TangentY_x (float) // Label 4 tangent + sizeY
    //   420: GridLabel4_TangentY_y (float)
    //   424: GridLabel4_TangentY_z (float)
    //   428: GridLabel4_TangentY_w (float)
    //   432: GridLabel5_PosTangentX_x (float) // Label 5 position + sizeX
    //   436: GridLabel5_PosTangentX_y (float)
    //   440: GridLabel5_PosTangentX_z (float)
    //   444: GridLabel5_PosTangentX_w (float)
    //   448: GridLabel5_TangentY_x (float) // Label 5 tangent + sizeY
    //   452: GridLabel5_TangentY_y (float)
    //   456: GridLabel5_TangentY_z (float)
    //   460: GridLabel5_TangentY_w (float)
    //   464: GridLabel6_PosTangentX_x (float) // Label 6 position + sizeX
    //   468: GridLabel6_PosTangentX_y (float)
    //   472: GridLabel6_PosTangentX_z (float)
    //   476: GridLabel6_PosTangentX_w (float)
    //   480: GridLabel6_TangentY_x (float) // Label 6 tangent + sizeY
    //   484: GridLabel6_TangentY_y (float)
    //   488: GridLabel6_TangentY_z (float)
    //   492: GridLabel6_TangentY_w (float)
    //   496: GridLabel7_PosTangentX_x (float) // Label 7 position + sizeX
    //   500: GridLabel7_PosTangentX_y (float)
    //   504: GridLabel7_PosTangentX_z (float)
    //   508: GridLabel7_PosTangentX_w (float)
    //   512: GridLabel7_TangentY_x (float) // Label 7 tangent + sizeY
    //   516: GridLabel7_TangentY_y (float)
    //   520: GridLabel7_TangentY_z (float)
    //   524: GridLabel7_TangentY_w (float)
    //   528: GridLabel8_PosTangentX_x (float) // Label 8 position + sizeX
    //   532: GridLabel8_PosTangentX_y (float)
    //   536: GridLabel8_PosTangentX_z (float)
    //   540: GridLabel8_PosTangentX_w (float)
    //   544: GridLabel8_TangentY_x (float) // Label 8 tangent + sizeY
    //   548: GridLabel8_TangentY_y (float)
    //   552: GridLabel8_TangentY_z (float)
    //   556: GridLabel8_TangentY_w (float)
    //   560: GridLabel9_PosTangentX_x (float) // Label 9 position + sizeX
    //   564: GridLabel9_PosTangentX_y (float)
    //   568: GridLabel9_PosTangentX_z (float)
    //   572: GridLabel9_PosTangentX_w (float)
    //   576: GridLabel9_TangentY_x (float) // Label 9 tangent + sizeY
    //   580: GridLabel9_TangentY_y (float)
    //   584: GridLabel9_TangentY_z (float)
    //   588: GridLabel9_TangentY_w (float)
    //   592: GridLabel10_PosTangentX_x (float) // Label 10 position + sizeX
    //   596: GridLabel10_PosTangentX_y (float)
    //   600: GridLabel10_PosTangentX_z (float)
    //   604: GridLabel10_PosTangentX_w (float)
    //   608: GridLabel10_TangentY_x (float) // Label 10 tangent + sizeY
    //   612: GridLabel10_TangentY_y (float)
    //   616: GridLabel10_TangentY_z (float)
    //   620: GridLabel10_TangentY_w (float)
    //   624: GridLabel11_PosTangentX_x (float) // Label 11 position + sizeX
    //   628: GridLabel11_PosTangentX_y (float)
    //   632: GridLabel11_PosTangentX_z (float)
    //   636: GridLabel11_PosTangentX_w (float)
    //   640: GridLabel11_TangentY_x (float) // Label 11 tangent + sizeY
    //   644: GridLabel11_TangentY_y (float)
    //   648: GridLabel11_TangentY_z (float)
    //   652: GridLabel11_TangentY_w (float)
    //   656: GridLabelDebugMask (uint32_t) // Bit mask for debug visualization
    //   660: LabelIntensity0 (float) // Label 0 brightness
    //   664: LabelIntensity1 (float) // Label 1 brightness
    //   668: LabelIntensity2 (float) // Label 2 brightness
    //   672: LabelIntensity3 (float) // Label 3 brightness
    //   676: LabelIntensity4 (float) // Label 4 brightness
    //   680: LabelIntensity5 (float) // Label 5 brightness
    //   684: LabelIntensity6 (float) // Label 6 brightness
    //   688: LabelIntensity7 (float) // Label 7 brightness
    //   692: LabelIntensity8 (float) // Label 8 brightness
    //   696: LabelIntensity9 (float) // Label 9 brightness
    //   700: LabelIntensity10 (float) // Label 10 brightness
    //   704: LabelIntensity11 (float) // Label 11 brightness
    //   708: LabelColor0 (uint32_t) // Label 0 color override (ARGB)
    //   712: LabelColor1 (uint32_t) // Label 1 color override (ARGB)
    //   716: LabelColor2 (uint32_t) // Label 2 color override (ARGB)
    //   720: LabelColor3 (uint32_t) // Label 3 color override (ARGB)
    //   724: LabelColor4 (uint32_t) // Label 4 color override (ARGB)
    //   728: LabelColor5 (uint32_t) // Label 5 color override (ARGB)
    //   732: LabelColor6 (uint32_t) // Label 6 color override (ARGB)
    //   736: LabelColor7 (uint32_t) // Label 7 color override (ARGB)
    //   740: LabelColor8 (uint32_t) // Label 8 color override (ARGB)
    //   744: LabelColor9 (uint32_t) // Label 9 color override (ARGB)
    //   748: LabelColor10 (uint32_t) // Label 10 color override (ARGB)
    //   752: LabelColor11 (uint32_t) // Label 11 color override (ARGB)
    //   756: VesselTargetEnabled (int32_t) // Show vessel target selector
    //   760: VesselTargetHash (float) // Hash for flicker variation
    //   764: _padVessel1 (float) // Padding
    //   768: _padVessel2 (float) // Padding
    //   772: _auto_pad1 (float) // Auto-inserted for alignment [PADDING]
    //   776: VesselTargetCircleCenterX (float) // Vessel target circle X
    //   780: VesselTargetCircleCenterY (float) // Vessel target circle Y
    //   784: VesselTargetCircleT (float) // Vessel target animation time 0-1
    //   788: VesselTargetCircleIntensity (float) // Vessel target circle brightness
    //   792: VesselTargetCircleThickness (float) // Vessel target circle line thickness
    //   796: VesselTargetCircleRadius (float) // Vessel target circle radius
    //   800: _padVessel3 (float) // Padding
    //   804: _padVessel4 (float) // Padding
    //   808: _padVessel5 (float) // Padding
    //   812: _padVessel6 (float) // Padding
    //   816: VesselTargetBoxTopLeftX (float) // Vessel target box X
    //   820: VesselTargetBoxTopLeftY (float) // Vessel target box Y
    //   824: VesselTargetBoxSizeX (float) // Vessel target box width
    //   828: VesselTargetBoxSizeY (float) // Vessel target box height
    //   832: VesselTargetBoxThickness (float) // Vessel target box line thickness
    //   836: _padVessel7 (float) // Padding
    //   840: VesselTargetTextOriginX (float) // Vessel target text position X
    //   844: VesselTargetTextOriginY (float) // Vessel target text position Y
    //   848: VesselTargetTextAreaSizeX (float) // Vessel target text area width
    //   852: VesselTargetTextAreaSizeY (float) // Vessel target text area height
    //   856: VesselTargetTextT (float) // Vessel target text animation time
    //   860: AnimatedLabelIntensity (float) // Generic intensity for animated labels (0-1)
    //   864: _padAnimated1 (float) // Padding
    //   868: _padAnimated2 (float) // Padding
    //   872: _padAnimated3 (float) // Padding to align to 16 bytes
    //   876: NavballEnabledMask (int32_t) // Bits 0-6: prograde, retrograde, normal, antinormal, radial_in, radial_out, maneuver
    //   880: NavballOffscreenMode (int32_t) // 0=world-space (disappear off-screen), 1=edge-clamp
    //   884: NavballIconSize (float) // Screen-space size in NDC units
    //   888: NavballIconThickness (float) // SDF edge thickness
    //   892: NavballMinIntensity (float) // Minimum intensity when far off-center (default 0.33)
    //   896: NavballMaxAngle (float) // Angle for min intensity in degrees (default 90)
    //   900: NavballHysteresisMargin (float) // Buffer zone for edge transition (default 0.05)
    //   904: _padNavball1 (float) // Padding to 16-byte boundary
    //   908: _auto_pad2 (float) // Auto-inserted for alignment [PADDING]
    //   912: NavballIcon0_X (float) // Screen X in NDC (-aspect to aspect)
    //   916: NavballIcon0_Y (float) // Screen Y in NDC (-1 to 1)
    //   920: NavballIcon0_Intensity (float) // Current intensity (0 = disabled/hidden)
    //   924: NavballIcon0_Color (uint32_t) // Packed ARGB color override (0 = use grid color)
    //   928: NavballIcon1_X (float) // Screen X in NDC
    //   932: NavballIcon1_Y (float) // Screen Y in NDC
    //   936: NavballIcon1_Intensity (float) // Current intensity
    //   940: NavballIcon1_Color (uint32_t) // Packed ARGB color override
    //   944: NavballIcon2_X (float) // Screen X in NDC
    //   948: NavballIcon2_Y (float) // Screen Y in NDC
    //   952: NavballIcon2_Intensity (float) // Current intensity
    //   956: NavballIcon2_Color (uint32_t) // Packed ARGB color override
    //   960: NavballIcon3_X (float) // Screen X in NDC
    //   964: NavballIcon3_Y (float) // Screen Y in NDC
    //   968: NavballIcon3_Intensity (float) // Current intensity
    //   972: NavballIcon3_Color (uint32_t) // Packed ARGB color override
    //   976: NavballIcon4_X (float) // Screen X in NDC
    //   980: NavballIcon4_Y (float) // Screen Y in NDC
    //   984: NavballIcon4_Intensity (float) // Current intensity
    //   988: NavballIcon4_Color (uint32_t) // Packed ARGB color override
    //   992: NavballIcon5_X (float) // Screen X in NDC
    //   996: NavballIcon5_Y (float) // Screen Y in NDC
    //   1000: NavballIcon5_Intensity (float) // Current intensity
    //   1004: NavballIcon5_Color (uint32_t) // Packed ARGB color override
    //   1008: NavballIcon6_X (float) // Screen X in NDC
    //   1012: NavballIcon6_Y (float) // Screen Y in NDC
    //   1016: NavballIcon6_Intensity (float) // Current intensity (0 when no node)
    //   1020: NavballIcon6_Color (uint32_t) // Packed ARGB color override

    float ResolutionX;
    float ResolutionY;
    float Time;
    float GridIntensity;
    float GridThickness;
    float ChromaticAberrationStrength;
    float VignetteStrength;
    float VignetteStart;
    float VignetteEnd;
    float PreRotationYaw;
    float PreRotationPitch;
    int32_t GridSizePreset;
    int32_t GridColorIndex;
    float _pad1;
    float _pad2;
    float _padAlignCamera;
    float CameraRightX;
    float CameraRightY;
    float CameraRightZ;
    float _pad3;
    float CameraUpX;
    float CameraUpY;
    float CameraUpZ;
    float _pad4;
    float CameraForwardX;
    float CameraForwardY;
    float CameraForwardZ;
    float _pad5;
    int32_t DebugShapesEnabled;
    float _pad6;
    float _pad7;
    float _pad8;
    float DebugCircleCenterX;
    float DebugCircleCenterY;
    float DebugCircleRadius;
    float DebugCircleThickness;
    float DebugBoxTopLeftX;
    float DebugBoxTopLeftY;
    float DebugBoxSizeX;
    float DebugBoxSizeY;
    float DebugBoxThickness;
    float DebugShapeIntensity;
    float _pad9;
    float FocalLength;
    int32_t SelectionCircleEnabled;
    float SelectionStarHash;
    float _padSelection2;
    float _padSelection3;
    float SelectionCircleCenterX;
    float SelectionCircleCenterY;
    float SelectionCircleT;
    float SelectionCircleIntensity;
    float SelectionCircleThickness;
    float SelectionCircleRadius;
    float _padSelection4;
    float _padSelection5;
    float _padSelection6;
    float _padSelection7;
    float TextOriginX;
    float TextOriginY;
    float TextAreaSizeX;
    float TextAreaSizeY;
    float SelectionTextT;
    uint32_t GridLabelEnabledMask;
    float _padGridMask1;
    float _padGridMask2;
    float _padGridMask3;
    float _padGridMask4;
    float GridLabel0_PosTangentX_x;
    float GridLabel0_PosTangentX_y;
    float GridLabel0_PosTangentX_z;
    float GridLabel0_PosTangentX_w;
    float GridLabel0_TangentY_x;
    float GridLabel0_TangentY_y;
    float GridLabel0_TangentY_z;
    float GridLabel0_TangentY_w;
    float GridLabel1_PosTangentX_x;
    float GridLabel1_PosTangentX_y;
    float GridLabel1_PosTangentX_z;
    float GridLabel1_PosTangentX_w;
    float GridLabel1_TangentY_x;
    float GridLabel1_TangentY_y;
    float GridLabel1_TangentY_z;
    float GridLabel1_TangentY_w;
    float GridLabel2_PosTangentX_x;
    float GridLabel2_PosTangentX_y;
    float GridLabel2_PosTangentX_z;
    float GridLabel2_PosTangentX_w;
    float GridLabel2_TangentY_x;
    float GridLabel2_TangentY_y;
    float GridLabel2_TangentY_z;
    float GridLabel2_TangentY_w;
    float GridLabel3_PosTangentX_x;
    float GridLabel3_PosTangentX_y;
    float GridLabel3_PosTangentX_z;
    float GridLabel3_PosTangentX_w;
    float GridLabel3_TangentY_x;
    float GridLabel3_TangentY_y;
    float GridLabel3_TangentY_z;
    float GridLabel3_TangentY_w;
    float GridLabel4_PosTangentX_x;
    float GridLabel4_PosTangentX_y;
    float GridLabel4_PosTangentX_z;
    float GridLabel4_PosTangentX_w;
    float GridLabel4_TangentY_x;
    float GridLabel4_TangentY_y;
    float GridLabel4_TangentY_z;
    float GridLabel4_TangentY_w;
    float GridLabel5_PosTangentX_x;
    float GridLabel5_PosTangentX_y;
    float GridLabel5_PosTangentX_z;
    float GridLabel5_PosTangentX_w;
    float GridLabel5_TangentY_x;
    float GridLabel5_TangentY_y;
    float GridLabel5_TangentY_z;
    float GridLabel5_TangentY_w;
    float GridLabel6_PosTangentX_x;
    float GridLabel6_PosTangentX_y;
    float GridLabel6_PosTangentX_z;
    float GridLabel6_PosTangentX_w;
    float GridLabel6_TangentY_x;
    float GridLabel6_TangentY_y;
    float GridLabel6_TangentY_z;
    float GridLabel6_TangentY_w;
    float GridLabel7_PosTangentX_x;
    float GridLabel7_PosTangentX_y;
    float GridLabel7_PosTangentX_z;
    float GridLabel7_PosTangentX_w;
    float GridLabel7_TangentY_x;
    float GridLabel7_TangentY_y;
    float GridLabel7_TangentY_z;
    float GridLabel7_TangentY_w;
    float GridLabel8_PosTangentX_x;
    float GridLabel8_PosTangentX_y;
    float GridLabel8_PosTangentX_z;
    float GridLabel8_PosTangentX_w;
    float GridLabel8_TangentY_x;
    float GridLabel8_TangentY_y;
    float GridLabel8_TangentY_z;
    float GridLabel8_TangentY_w;
    float GridLabel9_PosTangentX_x;
    float GridLabel9_PosTangentX_y;
    float GridLabel9_PosTangentX_z;
    float GridLabel9_PosTangentX_w;
    float GridLabel9_TangentY_x;
    float GridLabel9_TangentY_y;
    float GridLabel9_TangentY_z;
    float GridLabel9_TangentY_w;
    float GridLabel10_PosTangentX_x;
    float GridLabel10_PosTangentX_y;
    float GridLabel10_PosTangentX_z;
    float GridLabel10_PosTangentX_w;
    float GridLabel10_TangentY_x;
    float GridLabel10_TangentY_y;
    float GridLabel10_TangentY_z;
    float GridLabel10_TangentY_w;
    float GridLabel11_PosTangentX_x;
    float GridLabel11_PosTangentX_y;
    float GridLabel11_PosTangentX_z;
    float GridLabel11_PosTangentX_w;
    float GridLabel11_TangentY_x;
    float GridLabel11_TangentY_y;
    float GridLabel11_TangentY_z;
    float GridLabel11_TangentY_w;
    uint32_t GridLabelDebugMask;
    float LabelIntensity0;
    float LabelIntensity1;
    float LabelIntensity2;
    float LabelIntensity3;
    float LabelIntensity4;
    float LabelIntensity5;
    float LabelIntensity6;
    float LabelIntensity7;
    float LabelIntensity8;
    float LabelIntensity9;
    float LabelIntensity10;
    float LabelIntensity11;
    uint32_t LabelColor0;
    uint32_t LabelColor1;
    uint32_t LabelColor2;
    uint32_t LabelColor3;
    uint32_t LabelColor4;
    uint32_t LabelColor5;
    uint32_t LabelColor6;
    uint32_t LabelColor7;
    uint32_t LabelColor8;
    uint32_t LabelColor9;
    uint32_t LabelColor10;
    uint32_t LabelColor11;
    int32_t VesselTargetEnabled;
    float VesselTargetHash;
    float _padVessel1;
    float _padVessel2;
    float _auto_pad1; // padding
    float VesselTargetCircleCenterX;
    float VesselTargetCircleCenterY;
    float VesselTargetCircleT;
    float VesselTargetCircleIntensity;
    float VesselTargetCircleThickness;
    float VesselTargetCircleRadius;
    float _padVessel3;
    float _padVessel4;
    float _padVessel5;
    float _padVessel6;
    float VesselTargetBoxTopLeftX;
    float VesselTargetBoxTopLeftY;
    float VesselTargetBoxSizeX;
    float VesselTargetBoxSizeY;
    float VesselTargetBoxThickness;
    float _padVessel7;
    float VesselTargetTextOriginX;
    float VesselTargetTextOriginY;
    float VesselTargetTextAreaSizeX;
    float VesselTargetTextAreaSizeY;
    float VesselTargetTextT;
    float AnimatedLabelIntensity;
    float _padAnimated1;
    float _padAnimated2;
    float _padAnimated3;
    int32_t NavballEnabledMask;
    int32_t NavballOffscreenMode;
    float NavballIconSize;
    float NavballIconThickness;
    float NavballMinIntensity;
    float NavballMaxAngle;
    float NavballHysteresisMargin;
    float _padNavball1;
    float _auto_pad2; // padding
    float NavballIcon0_X;
    float NavballIcon0_Y;
    float NavballIcon0_Intensity;
    uint32_t NavballIcon0_Color;
    float NavballIcon1_X;
    float NavballIcon1_Y;
    float NavballIcon1_Intensity;
    uint32_t NavballIcon1_Color;
    float NavballIcon2_X;
    float NavballIcon2_Y;
    float NavballIcon2_Intensity;
    uint32_t NavballIcon2_Color;
    float NavballIcon3_X;
    float NavballIcon3_Y;
    float NavballIcon3_Intensity;
    uint32_t NavballIcon3_Color;
    float NavballIcon4_X;
    float NavballIcon4_Y;
    float NavballIcon4_Intensity;
    uint32_t NavballIcon4_Color;
    float NavballIcon5_X;
    float NavballIcon5_Y;
    float NavballIcon5_Intensity;
    uint32_t NavballIcon5_Color;
    float NavballIcon6_X;
    float NavballIcon6_Y;
    float NavballIcon6_Intensity;
    uint32_t NavballIcon6_Color;
};
#pragma pack(pop)

// Static assertions to verify HLSL constant buffer alignment
static_assert(sizeof(KartographerParams) == 1024,
              "KartographerParams size mismatch - expected 1024 bytes");
static_assert(sizeof(KartographerParams) % 16 == 0,
              "KartographerParams must be 16-byte aligned for HLSL CB");
