// ============================================================================
// HLSL: KartographerParams
// Total Size: 1024 bytes (constant buffer)
// Generated by StructToolset - DO NOT EDIT MANUALLY
// ============================================================================

struct KartographerParams {
    // Field offsets (bytes):
    //     0: Resolution (float2) // Screen width in pixels
    //     8: Time (float) // Current time in seconds
    //    12: GridIntensity (float) // Grid line brightness
    //    16: GridThickness (float) // Grid line thickness
    //    20: ChromaticAberrationStrength (float) // CA effect strength
    //    24: VignetteStrength (float) // Vignette darkness
    //    28: VignetteStart (float) // Vignette inner radius
    //    32: VignetteEnd (float) // Vignette outer radius
    //    36: PreRotationYaw (float) // Grid yaw rotation
    //    40: PreRotationPitch (float) // Grid pitch rotation
    //    44: GridSizePreset (int) // Grid density preset
    //    48: GridColorIndex (int) // Grid color selection
    //    52: _pad1 (float) // Padding
    //    56: _pad2 (float) // Padding
    //    60: _padAlignCamera (float) // Align to 16 bytes
    //    64: CameraRight (float3) // Camera right vector X
    //    76: _pad3 (float) // Padding
    //    80: CameraUp (float3) // Camera up vector X
    //    92: _pad4 (float) // Padding
    //    96: CameraForward (float3) // Camera forward vector X
    //   108: _pad5 (float) // Padding
    //   112: DebugShapesEnabled (int) // Show debug overlays
    //   116: _pad6 (float) // Padding
    //   120: _pad7 (float) // Padding
    //   124: _pad8 (float) // Padding
    //   128: DebugCircleCenter (float2) // Debug circle X
    //   136: DebugCircleRadius (float) // Debug circle radius
    //   140: DebugCircleThickness (float) // Debug circle line thickness
    //   144: DebugBoxTopLeft (float2) // Debug box X
    //   152: DebugBoxSize (float2) // Debug box width
    //   160: DebugBoxThickness (float) // Debug box line thickness
    //   164: DebugShapeIntensity (float) // Debug shape brightness
    //   168: _pad9 (float) // Padding
    //   172: FocalLength (float) // Camera focal length
    //   176: SelectionCircleEnabled (int) // Show selection circle
    //   180: SelectionStarHash (float) // Hash for flicker variation
    //   184: _padSelection2 (float) // Padding
    //   188: _padSelection3 (float) // Padding
    //   192: SelectionCircleCenter (float2) // Selection circle X
    //   200: SelectionCircleT (float) // Animation time 0-1
    //   204: SelectionCircleIntensity (float) // Circle brightness
    //   208: SelectionCircleThickness (float) // Circle line thickness
    //   212: SelectionCircleRadius (float) // Circle radius
    //   216: _padSelection4 (float) // Padding
    //   220: _padSelection5 (float) // Padding
    //   224: _padSelection6 (float) // Padding
    //   228: _padSelection7 (float) // Padding
    //   232: TextOrigin (float2) // Text position X
    //   240: TextAreaSize (float2) // Text area width
    //   248: SelectionTextT (float) // Text animation time
    //   252: GridLabelEnabledMask (uint) // Bit mask for enabled labels
    //   256: _padGridMask1 (float) // Padding
    //   260: _padGridMask2 (float) // Padding
    //   264: _padGridMask3 (float) // Padding
    //   268: _padGridMask4 (float) // Padding to align labels to 16 bytes
    //   272: GridLabel0_PosTangentX (float4) // Label 0 position + sizeX
    //   288: GridLabel0_TangentY (float4) // Label 0 tangent + sizeY
    //   304: GridLabel1_PosTangentX (float4) // Label 1 position + sizeX
    //   320: GridLabel1_TangentY (float4) // Label 1 tangent + sizeY
    //   336: GridLabel2_PosTangentX (float4) // Label 2 position + sizeX
    //   352: GridLabel2_TangentY (float4) // Label 2 tangent + sizeY
    //   368: GridLabel3_PosTangentX (float4) // Label 3 position + sizeX
    //   384: GridLabel3_TangentY (float4) // Label 3 tangent + sizeY
    //   400: GridLabel4_PosTangentX (float4) // Label 4 position + sizeX
    //   416: GridLabel4_TangentY (float4) // Label 4 tangent + sizeY
    //   432: GridLabel5_PosTangentX (float4) // Label 5 position + sizeX
    //   448: GridLabel5_TangentY (float4) // Label 5 tangent + sizeY
    //   464: GridLabel6_PosTangentX (float4) // Label 6 position + sizeX
    //   480: GridLabel6_TangentY (float4) // Label 6 tangent + sizeY
    //   496: GridLabel7_PosTangentX (float4) // Label 7 position + sizeX
    //   512: GridLabel7_TangentY (float4) // Label 7 tangent + sizeY
    //   528: GridLabel8_PosTangentX (float4) // Label 8 position + sizeX
    //   544: GridLabel8_TangentY (float4) // Label 8 tangent + sizeY
    //   560: GridLabel9_PosTangentX (float4) // Label 9 position + sizeX
    //   576: GridLabel9_TangentY (float4) // Label 9 tangent + sizeY
    //   592: GridLabel10_PosTangentX (float4) // Label 10 position + sizeX
    //   608: GridLabel10_TangentY (float4) // Label 10 tangent + sizeY
    //   624: GridLabel11_PosTangentX (float4) // Label 11 position + sizeX
    //   640: GridLabel11_TangentY (float4) // Label 11 tangent + sizeY
    //   656: GridLabelDebugMask (uint) // Bit mask for debug visualization
    //   660: LabelIntensity0 (float) // Label 0 brightness
    //   664: LabelIntensity1 (float) // Label 1 brightness
    //   668: LabelIntensity2 (float) // Label 2 brightness
    //   672: LabelIntensity3 (float) // Label 3 brightness
    //   676: LabelIntensity4 (float) // Label 4 brightness
    //   680: LabelIntensity5 (float) // Label 5 brightness
    //   684: LabelIntensity6 (float) // Label 6 brightness
    //   688: LabelIntensity7 (float) // Label 7 brightness
    //   692: LabelIntensity8 (float) // Label 8 brightness
    //   696: LabelIntensity9 (float) // Label 9 brightness
    //   700: LabelIntensity10 (float) // Label 10 brightness
    //   704: LabelIntensity11 (float) // Label 11 brightness
    //   708: LabelColor0 (uint) // Label 0 color override (ARGB)
    //   712: LabelColor1 (uint) // Label 1 color override (ARGB)
    //   716: LabelColor2 (uint) // Label 2 color override (ARGB)
    //   720: LabelColor3 (uint) // Label 3 color override (ARGB)
    //   724: LabelColor4 (uint) // Label 4 color override (ARGB)
    //   728: LabelColor5 (uint) // Label 5 color override (ARGB)
    //   732: LabelColor6 (uint) // Label 6 color override (ARGB)
    //   736: LabelColor7 (uint) // Label 7 color override (ARGB)
    //   740: LabelColor8 (uint) // Label 8 color override (ARGB)
    //   744: LabelColor9 (uint) // Label 9 color override (ARGB)
    //   748: LabelColor10 (uint) // Label 10 color override (ARGB)
    //   752: LabelColor11 (uint) // Label 11 color override (ARGB)
    //   756: VesselTargetEnabled (int) // Show vessel target selector
    //   760: VesselTargetHash (float) // Hash for flicker variation
    //   764: _padVessel1 (float) // Padding
    //   768: _padVessel2 (float) // Padding
    //   776: VesselTargetCircleCenter (float2) // Vessel target circle X
    //   784: VesselTargetCircleT (float) // Vessel target animation time 0-1
    //   788: VesselTargetCircleIntensity (float) // Vessel target circle brightness
    //   792: VesselTargetCircleThickness (float) // Vessel target circle line thickness
    //   796: VesselTargetCircleRadius (float) // Vessel target circle radius
    //   800: _padVessel3 (float) // Padding
    //   804: _padVessel4 (float) // Padding
    //   808: _padVessel5 (float) // Padding
    //   812: _padVessel6 (float) // Padding
    //   816: VesselTargetBoxTopLeft (float2) // Vessel target box X
    //   824: VesselTargetBoxSize (float2) // Vessel target box width
    //   832: VesselTargetBoxThickness (float) // Vessel target box line thickness
    //   836: _padVessel7 (float) // Padding
    //   840: VesselTargetTextOrigin (float2) // Vessel target text position X
    //   848: VesselTargetTextAreaSize (float2) // Vessel target text area width
    //   856: VesselTargetTextT (float) // Vessel target text animation time
    //   860: AnimatedLabelIntensity (float) // Generic intensity for animated labels (0-1)
    //   864: _padAnimated1 (float) // Padding
    //   868: _padAnimated2 (float) // Padding
    //   872: _padAnimated3 (float) // Padding to align to 16 bytes
    //   876: NavballEnabledMask (int) // Bits 0-6: prograde, retrograde, normal, antinormal, radial_in, radial_out, maneuver
    //   880: NavballOffscreenMode (int) // 0=world-space (disappear off-screen), 1=edge-clamp
    //   884: NavballIconSize (float) // Screen-space size in NDC units
    //   888: NavballIconThickness (float) // SDF edge thickness
    //   892: NavballMinIntensity (float) // Minimum intensity when far off-center (default 0.33)
    //   896: NavballMaxAngle (float) // Angle for min intensity in degrees (default 90)
    //   900: NavballHysteresisMargin (float) // Buffer zone for edge transition (default 0.05)
    //   904: _padNavball1 (float) // Padding to 16-byte boundary
    //   912: NavballIcon0 (float2) // Screen X in NDC (-aspect to aspect)
    //   920: NavballIcon0_Intensity (float) // Current intensity (0 = disabled/hidden)
    //   924: NavballIcon0_Color (uint) // Packed ARGB color override (0 = use grid color)
    //   928: NavballIcon1 (float2) // Screen X in NDC
    //   936: NavballIcon1_Intensity (float) // Current intensity
    //   940: NavballIcon1_Color (uint) // Packed ARGB color override
    //   944: NavballIcon2 (float2) // Screen X in NDC
    //   952: NavballIcon2_Intensity (float) // Current intensity
    //   956: NavballIcon2_Color (uint) // Packed ARGB color override
    //   960: NavballIcon3 (float2) // Screen X in NDC
    //   968: NavballIcon3_Intensity (float) // Current intensity
    //   972: NavballIcon3_Color (uint) // Packed ARGB color override
    //   976: NavballIcon4 (float2) // Screen X in NDC
    //   984: NavballIcon4_Intensity (float) // Current intensity
    //   988: NavballIcon4_Color (uint) // Packed ARGB color override
    //   992: NavballIcon5 (float2) // Screen X in NDC
    //   1000: NavballIcon5_Intensity (float) // Current intensity
    //   1004: NavballIcon5_Color (uint) // Packed ARGB color override
    //   1008: NavballIcon6 (float2) // Screen X in NDC
    //   1016: NavballIcon6_Intensity (float) // Current intensity (0 when no node)
    //   1020: NavballIcon6_Color (uint) // Packed ARGB color override

    float2 Resolution;
    float Time;
    float GridIntensity;
    float GridThickness;
    float ChromaticAberrationStrength;
    float VignetteStrength;
    float VignetteStart;
    float VignetteEnd;
    float PreRotationYaw;
    float PreRotationPitch;
    int GridSizePreset;
    int GridColorIndex;
    float _pad1;
    float _pad2;
    float _padAlignCamera;
    float3 CameraRight;
    float _pad3;
    float3 CameraUp;
    float _pad4;
    float3 CameraForward;
    float _pad5;
    int DebugShapesEnabled;
    float _pad6;
    float _pad7;
    float _pad8;
    float2 DebugCircleCenter;
    float DebugCircleRadius;
    float DebugCircleThickness;
    float2 DebugBoxTopLeft;
    float2 DebugBoxSize;
    float DebugBoxThickness;
    float DebugShapeIntensity;
    float _pad9;
    float FocalLength;
    int SelectionCircleEnabled;
    float SelectionStarHash;
    float _padSelection2;
    float _padSelection3;
    float2 SelectionCircleCenter;
    float SelectionCircleT;
    float SelectionCircleIntensity;
    float SelectionCircleThickness;
    float SelectionCircleRadius;
    float _padSelection4;
    float _padSelection5;
    float _padSelection6;
    float _padSelection7;
    float2 TextOrigin;
    float2 TextAreaSize;
    float SelectionTextT;
    uint GridLabelEnabledMask;
    float _padGridMask1;
    float _padGridMask2;
    float _padGridMask3;
    float _padGridMask4;
    float4 GridLabel0_PosTangentX;
    float4 GridLabel0_TangentY;
    float4 GridLabel1_PosTangentX;
    float4 GridLabel1_TangentY;
    float4 GridLabel2_PosTangentX;
    float4 GridLabel2_TangentY;
    float4 GridLabel3_PosTangentX;
    float4 GridLabel3_TangentY;
    float4 GridLabel4_PosTangentX;
    float4 GridLabel4_TangentY;
    float4 GridLabel5_PosTangentX;
    float4 GridLabel5_TangentY;
    float4 GridLabel6_PosTangentX;
    float4 GridLabel6_TangentY;
    float4 GridLabel7_PosTangentX;
    float4 GridLabel7_TangentY;
    float4 GridLabel8_PosTangentX;
    float4 GridLabel8_TangentY;
    float4 GridLabel9_PosTangentX;
    float4 GridLabel9_TangentY;
    float4 GridLabel10_PosTangentX;
    float4 GridLabel10_TangentY;
    float4 GridLabel11_PosTangentX;
    float4 GridLabel11_TangentY;
    uint GridLabelDebugMask;
    float LabelIntensity0;
    float LabelIntensity1;
    float LabelIntensity2;
    float LabelIntensity3;
    float LabelIntensity4;
    float LabelIntensity5;
    float LabelIntensity6;
    float LabelIntensity7;
    float LabelIntensity8;
    float LabelIntensity9;
    float LabelIntensity10;
    float LabelIntensity11;
    uint LabelColor0;
    uint LabelColor1;
    uint LabelColor2;
    uint LabelColor3;
    uint LabelColor4;
    uint LabelColor5;
    uint LabelColor6;
    uint LabelColor7;
    uint LabelColor8;
    uint LabelColor9;
    uint LabelColor10;
    uint LabelColor11;
    int VesselTargetEnabled;
    float VesselTargetHash;
    float _padVessel1;
    float _padVessel2;
    float2 VesselTargetCircleCenter;
    float VesselTargetCircleT;
    float VesselTargetCircleIntensity;
    float VesselTargetCircleThickness;
    float VesselTargetCircleRadius;
    float _padVessel3;
    float _padVessel4;
    float _padVessel5;
    float _padVessel6;
    float2 VesselTargetBoxTopLeft;
    float2 VesselTargetBoxSize;
    float VesselTargetBoxThickness;
    float _padVessel7;
    float2 VesselTargetTextOrigin;
    float2 VesselTargetTextAreaSize;
    float VesselTargetTextT;
    float AnimatedLabelIntensity;
    float _padAnimated1;
    float _padAnimated2;
    float _padAnimated3;
    int NavballEnabledMask;
    int NavballOffscreenMode;
    float NavballIconSize;
    float NavballIconThickness;
    float NavballMinIntensity;
    float NavballMaxAngle;
    float NavballHysteresisMargin;
    float _padNavball1;
    float2 NavballIcon0;
    float NavballIcon0_Intensity;
    uint NavballIcon0_Color;
    float2 NavballIcon1;
    float NavballIcon1_Intensity;
    uint NavballIcon1_Color;
    float2 NavballIcon2;
    float NavballIcon2_Intensity;
    uint NavballIcon2_Color;
    float2 NavballIcon3;
    float NavballIcon3_Intensity;
    uint NavballIcon3_Color;
    float2 NavballIcon4;
    float NavballIcon4_Intensity;
    uint NavballIcon4_Color;
    float2 NavballIcon5;
    float NavballIcon5_Intensity;
    uint NavballIcon5_Color;
    float2 NavballIcon6;
    float NavballIcon6_Intensity;
    uint NavballIcon6_Color;
};

// Constant buffer declaration:
// cbuffer KartographerParamsBuffer : register(b0) {
//     KartographerParams g_kartographerParams;
// }
