// ============================================================================
// C++: KartographerParams
// Total Size: 880 bytes (constant buffer)
// Generated by struct generator - DO NOT EDIT MANUALLY
// ============================================================================

#pragma once
#include <cstdint>

// HLSL-style vector types for C++
struct float2 { float x, y; };
struct float3 { float x, y, z; };
struct float4 { float x, y, z, w; };

struct KartographerParams {
    // Field offsets (bytes):
    //     0: ResolutionX (float) // Screen width in pixels
    //     4: ResolutionY (float) // Screen height in pixels
    //     8: Time (float) // Current time in seconds
    //    12: GridIntensity (float) // Grid line brightness
    //    16: GridThickness (float) // Grid line thickness
    //    20: ChromaticAberrationStrength (float) // CA effect strength
    //    24: VignetteStrength (float) // Vignette darkness
    //    28: VignetteStart (float) // Vignette inner radius
    //    32: VignetteEnd (float) // Vignette outer radius
    //    36: PreRotationYaw (float) // Grid yaw rotation
    //    40: PreRotationPitch (float) // Grid pitch rotation
    //    44: GridSizePreset (int) // Grid density preset
    //    48: GridColorIndex (int) // Grid color selection
    //    52: _pad1 (float) // Padding
    //    56: _pad2 (float) // Padding
    //    60: _padAlignCamera (float) // Align to 16 bytes
    //    64: CameraRightX (float) // Camera right vector X
    //    68: CameraRightY (float) // Camera right vector Y
    //    72: CameraRightZ (float) // Camera right vector Z
    //    76: _pad3 (float) // Padding
    //    80: CameraUpX (float) // Camera up vector X
    //    84: CameraUpY (float) // Camera up vector Y
    //    88: CameraUpZ (float) // Camera up vector Z
    //    92: _pad4 (float) // Padding
    //    96: CameraForwardX (float) // Camera forward vector X
    //   100: CameraForwardY (float) // Camera forward vector Y
    //   104: CameraForwardZ (float) // Camera forward vector Z
    //   108: _pad5 (float) // Padding
    //   112: DebugShapesEnabled (int) // Show debug overlays
    //   116: _pad6 (float) // Padding
    //   120: _pad7 (float) // Padding
    //   124: _pad8 (float) // Padding
    //   128: DebugCircleCenterX (float) // Debug circle X
    //   132: DebugCircleCenterY (float) // Debug circle Y
    //   136: DebugCircleRadius (float) // Debug circle radius
    //   140: DebugCircleThickness (float) // Debug circle line thickness
    //   144: DebugBoxTopLeftX (float) // Debug box X
    //   148: DebugBoxTopLeftY (float) // Debug box Y
    //   152: DebugBoxSizeX (float) // Debug box width
    //   156: DebugBoxSizeY (float) // Debug box height
    //   160: DebugBoxThickness (float) // Debug box line thickness
    //   164: DebugShapeIntensity (float) // Debug shape brightness
    //   168: _pad9 (float) // Padding
    //   172: FocalLength (float) // Camera focal length
    //   176: SelectionCircleEnabled (int) // Show selection circle
    //   180: _padSelection1 (float) // Padding
    //   184: _padSelection2 (float) // Padding
    //   188: _padSelection3 (float) // Padding
    //   192: SelectionCircleCenterX (float) // Selection circle X
    //   196: SelectionCircleCenterY (float) // Selection circle Y
    //   200: SelectionCircleT (float) // Animation time 0-1
    //   204: SelectionCircleIntensity (float) // Circle brightness
    //   208: SelectionCircleThickness (float) // Circle line thickness
    //   212: SelectionCircleRadius (float) // Circle radius
    //   216: _padSelection4 (float) // Padding
    //   220: _padSelection5 (float) // Padding
    //   224: _padSelection6 (float) // Padding
    //   228: _padSelection7 (float) // Padding
    //   232: TextOriginX (float) // Text position X
    //   236: TextOriginY (float) // Text position Y
    //   240: TextAreaSizeX (float) // Text area width
    //   244: TextAreaSizeY (float) // Text area height
    //   248: SelectionTextT (float) // Text animation time
    //   252: GridLabelEnabledMask (uint) // Bit mask for enabled labels
    //   256: _padGridMask1 (float) // Padding
    //   260: _padGridMask2 (float) // Padding
    //   264: _padGridMask3 (float) // Padding
    //   268: _padGridMask4 (float) // Padding to align labels to 16 bytes
    //   272: GridLabel0_PosTangentX (float4) // Label 0 position + sizeX
    //   288: GridLabel0_TangentY (float4) // Label 0 tangent + sizeY
    //   304: GridLabel1_PosTangentX (float4) // Label 1 position + sizeX
    //   320: GridLabel1_TangentY (float4) // Label 1 tangent + sizeY
    //   336: GridLabel2_PosTangentX (float4) // Label 2 position + sizeX
    //   352: GridLabel2_TangentY (float4) // Label 2 tangent + sizeY
    //   368: GridLabel3_PosTangentX (float4) // Label 3 position + sizeX
    //   384: GridLabel3_TangentY (float4) // Label 3 tangent + sizeY
    //   400: GridLabel4_PosTangentX (float4) // Label 4 position + sizeX
    //   416: GridLabel4_TangentY (float4) // Label 4 tangent + sizeY
    //   432: GridLabel5_PosTangentX (float4) // Label 5 position + sizeX
    //   448: GridLabel5_TangentY (float4) // Label 5 tangent + sizeY
    //   464: GridLabel6_PosTangentX (float4) // Label 6 position + sizeX
    //   480: GridLabel6_TangentY (float4) // Label 6 tangent + sizeY
    //   496: GridLabel7_PosTangentX (float4) // Label 7 position + sizeX
    //   512: GridLabel7_TangentY (float4) // Label 7 tangent + sizeY
    //   528: GridLabel8_PosTangentX (float4) // Label 8 position + sizeX
    //   544: GridLabel8_TangentY (float4) // Label 8 tangent + sizeY
    //   560: GridLabel9_PosTangentX (float4) // Label 9 position + sizeX
    //   576: GridLabel9_TangentY (float4) // Label 9 tangent + sizeY
    //   592: GridLabel10_PosTangentX (float4) // Label 10 position + sizeX
    //   608: GridLabel10_TangentY (float4) // Label 10 tangent + sizeY
    //   624: GridLabel11_PosTangentX (float4) // Label 11 position + sizeX
    //   640: GridLabel11_TangentY (float4) // Label 11 tangent + sizeY
    //   656: GridLabelDebugMask (uint) // Bit mask for debug visualization
    //   660: LabelIntensity0 (float) // Label 0 brightness
    //   664: LabelIntensity1 (float) // Label 1 brightness
    //   668: LabelIntensity2 (float) // Label 2 brightness
    //   672: LabelIntensity3 (float) // Label 3 brightness
    //   676: LabelIntensity4 (float) // Label 4 brightness
    //   680: LabelIntensity5 (float) // Label 5 brightness
    //   684: LabelIntensity6 (float) // Label 6 brightness
    //   688: LabelIntensity7 (float) // Label 7 brightness
    //   692: LabelIntensity8 (float) // Label 8 brightness
    //   696: LabelIntensity9 (float) // Label 9 brightness
    //   700: LabelIntensity10 (float) // Label 10 brightness
    //   704: LabelIntensity11 (float) // Label 11 brightness
    //   708: LabelColor0 (uint) // Label 0 color override (ARGB)
    //   712: LabelColor1 (uint) // Label 1 color override (ARGB)
    //   716: LabelColor2 (uint) // Label 2 color override (ARGB)
    //   720: LabelColor3 (uint) // Label 3 color override (ARGB)
    //   724: LabelColor4 (uint) // Label 4 color override (ARGB)
    //   728: LabelColor5 (uint) // Label 5 color override (ARGB)
    //   732: LabelColor6 (uint) // Label 6 color override (ARGB)
    //   736: LabelColor7 (uint) // Label 7 color override (ARGB)
    //   740: LabelColor8 (uint) // Label 8 color override (ARGB)
    //   744: LabelColor9 (uint) // Label 9 color override (ARGB)
    //   748: LabelColor10 (uint) // Label 10 color override (ARGB)
    //   752: LabelColor11 (uint) // Label 11 color override (ARGB)
    //   756: VesselTargetEnabled (int) // Show vessel target selector
    //   760: VesselTargetHash (float) // Hash for flicker variation
    //   764: _padVessel1 (float) // Padding
    //   768: _padVessel2 (float) // Padding
    //   772: VesselTargetCircleCenterX (float) // Vessel target circle X
    //   776: VesselTargetCircleCenterY (float) // Vessel target circle Y
    //   780: VesselTargetCircleT (float) // Vessel target animation time 0-1
    //   784: VesselTargetCircleIntensity (float) // Vessel target circle brightness
    //   788: VesselTargetCircleThickness (float) // Vessel target circle line thickness
    //   792: VesselTargetCircleRadius (float) // Vessel target circle radius
    //   796: _padVessel3 (float) // Padding
    //   800: _padVessel4 (float) // Padding
    //   804: _padVessel5 (float) // Padding
    //   808: _padVessel6 (float) // Padding
    //   812: VesselTargetBoxTopLeftX (float) // Vessel target box X
    //   816: VesselTargetBoxTopLeftY (float) // Vessel target box Y
    //   820: VesselTargetBoxSizeX (float) // Vessel target box width
    //   824: VesselTargetBoxSizeY (float) // Vessel target box height
    //   828: VesselTargetBoxThickness (float) // Vessel target box line thickness
    //   832: _padVessel7 (float) // Padding
    //   836: VesselTargetTextOriginX (float) // Vessel target text position X
    //   840: VesselTargetTextOriginY (float) // Vessel target text position Y
    //   844: VesselTargetTextAreaSizeX (float) // Vessel target text area width
    //   848: VesselTargetTextAreaSizeY (float) // Vessel target text area height
    //   852: VesselTargetTextT (float) // Vessel target text animation time
    //   856: AnimatedLabelIntensity (float) // Generic intensity for animated labels (0-1)
    //   860: _padAnimated1 (float) // Padding
    //   864: _padAnimated2 (float) // Padding
    //   868: _padAnimated3 (float) // Padding to align to 16 bytes

    float ResolutionX;
    float ResolutionY;
    float Time;
    float GridIntensity;
    float GridThickness;
    float ChromaticAberrationStrength;
    float VignetteStrength;
    float VignetteStart;
    float VignetteEnd;
    float PreRotationYaw;
    float PreRotationPitch;
    int GridSizePreset;
    int GridColorIndex;
    float _pad1;
    float _pad2;
    float _padAlignCamera;
    float CameraRightX;
    float CameraRightY;
    float CameraRightZ;
    float _pad3;
    float CameraUpX;
    float CameraUpY;
    float CameraUpZ;
    float _pad4;
    float CameraForwardX;
    float CameraForwardY;
    float CameraForwardZ;
    float _pad5;
    int DebugShapesEnabled;
    float _pad6;
    float _pad7;
    float _pad8;
    float DebugCircleCenterX;
    float DebugCircleCenterY;
    float DebugCircleRadius;
    float DebugCircleThickness;
    float DebugBoxTopLeftX;
    float DebugBoxTopLeftY;
    float DebugBoxSizeX;
    float DebugBoxSizeY;
    float DebugBoxThickness;
    float DebugShapeIntensity;
    float _pad9;
    float FocalLength;
    int SelectionCircleEnabled;
    float _padSelection1;
    float _padSelection2;
    float _padSelection3;
    float SelectionCircleCenterX;
    float SelectionCircleCenterY;
    float SelectionCircleT;
    float SelectionCircleIntensity;
    float SelectionCircleThickness;
    float SelectionCircleRadius;
    float _padSelection4;
    float _padSelection5;
    float _padSelection6;
    float _padSelection7;
    float TextOriginX;
    float TextOriginY;
    float TextAreaSizeX;
    float TextAreaSizeY;
    float SelectionTextT;
    uint32_t GridLabelEnabledMask;
    float _padGridMask1;
    float _padGridMask2;
    float _padGridMask3;
    float _padGridMask4;
    float4 GridLabel0_PosTangentX;
    float4 GridLabel0_TangentY;
    float4 GridLabel1_PosTangentX;
    float4 GridLabel1_TangentY;
    float4 GridLabel2_PosTangentX;
    float4 GridLabel2_TangentY;
    float4 GridLabel3_PosTangentX;
    float4 GridLabel3_TangentY;
    float4 GridLabel4_PosTangentX;
    float4 GridLabel4_TangentY;
    float4 GridLabel5_PosTangentX;
    float4 GridLabel5_TangentY;
    float4 GridLabel6_PosTangentX;
    float4 GridLabel6_TangentY;
    float4 GridLabel7_PosTangentX;
    float4 GridLabel7_TangentY;
    float4 GridLabel8_PosTangentX;
    float4 GridLabel8_TangentY;
    float4 GridLabel9_PosTangentX;
    float4 GridLabel9_TangentY;
    float4 GridLabel10_PosTangentX;
    float4 GridLabel10_TangentY;
    float4 GridLabel11_PosTangentX;
    float4 GridLabel11_TangentY;
    uint32_t GridLabelDebugMask;
    float LabelIntensity0;
    float LabelIntensity1;
    float LabelIntensity2;
    float LabelIntensity3;
    float LabelIntensity4;
    float LabelIntensity5;
    float LabelIntensity6;
    float LabelIntensity7;
    float LabelIntensity8;
    float LabelIntensity9;
    float LabelIntensity10;
    float LabelIntensity11;
    uint32_t LabelColor0;
    uint32_t LabelColor1;
    uint32_t LabelColor2;
    uint32_t LabelColor3;
    uint32_t LabelColor4;
    uint32_t LabelColor5;
    uint32_t LabelColor6;
    uint32_t LabelColor7;
    uint32_t LabelColor8;
    uint32_t LabelColor9;
    uint32_t LabelColor10;
    uint32_t LabelColor11;
    int VesselTargetEnabled;
    float VesselTargetHash;
    float _padVessel1;
    float _padVessel2;
    float VesselTargetCircleCenterX;
    float VesselTargetCircleCenterY;
    float VesselTargetCircleT;
    float VesselTargetCircleIntensity;
    float VesselTargetCircleThickness;
    float VesselTargetCircleRadius;
    float _padVessel3;
    float _padVessel4;
    float _padVessel5;
    float _padVessel6;
    float VesselTargetBoxTopLeftX;
    float VesselTargetBoxTopLeftY;
    float VesselTargetBoxSizeX;
    float VesselTargetBoxSizeY;
    float VesselTargetBoxThickness;
    float _padVessel7;
    float VesselTargetTextOriginX;
    float VesselTargetTextOriginY;
    float VesselTargetTextAreaSizeX;
    float VesselTargetTextAreaSizeY;
    float VesselTargetTextT;
    float AnimatedLabelIntensity;
    float _padAnimated1;
    float _padAnimated2;
    float _padAnimated3;
};

// Static assertions to verify HLSL constant buffer alignment
static_assert(sizeof(KartographerParams) == 880, 
              "KartographerParams size mismatch - expected 880 bytes");
static_assert(sizeof(KartographerParams) % 16 == 0,
              "KartographerParams must be 16-byte aligned for HLSL CB");
